---
##### managing_users_and_groups.yml example playbook variables #####

# "neb_volume" module variables

# Name of the nPod to target for managing volumes
npod_name: "Kubernetes_test_pod"

# Name of a volume to manage
volume_name: "test_volume"

# Set the mirrored property of the volume: true:false
volume_mirrored: true

# Volume size in bytes
volume_size: 1000000000000

# If specified, will set the owner SPU for a volume
volume_owner_spu_serial:

# If specified, will set the backup SPU for a volume
# Applicable only if `volume_mirrored: true`
volume_backup_spu_serial:

# State of the volume: present:absent
volume_state: "present"

# "neb_volume_access" module variables
# neb_lun_status: Determines LUN export availability in the nPod
# Possible values:
# - present -> Export the volume to all nPod servers. Same as "all"
# - absent -> Remove the volume export from all nPod servers.
# - all -> Export the volume to all nPod servers. Same as "present"
# - host -> Export the volume to a single, specific server; host_uuid must be provided.
# - local -> Export the volume only to the server owning the volume
neb_lun_status: "present"
